# Generated by Django 3.1.6 on 2021-03-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory_name',
            field=models.CharField(blank=True, default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory_slug',
            field=models.CharField(default=True, max_length=200, unique=True),
        ),
    ]
