# Generated by Django 3.1.6 on 2021-03-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0004_auto_20210314_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory_slug',
        ),
    ]
