# Generated by Django 3.1.6 on 2021-03-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0005_auto_20210314_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory_name',
            field=models.CharField(blank=True, default=models.CharField(max_length=200), max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory_slug',
            field=models.CharField(default=models.CharField(max_length=200, unique=True), max_length=200, unique=True),
        ),
    ]
